import React from 'react';
import type { Metadata } from 'next';
import Script from 'next/script';
import './globals.css';
import '@/styles/styles.css';
import '@/styles/css/animate.min.css';
import '@/styles/css/bootstrap.css';
import '@/styles/css/bootstrap-select.min.css';
import '@/styles/css/animation.css';
import '@/styles/css/style.css';

import '@/icon/style.css';
import '@/font/fonts.css';


export const metadata: Metadata = {
  title: 'App admin dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <head>
        <link rel="shortcut icon" href="/images/favicon.png" />
        <link rel="apple-touch-icon" href="/images/favicon.png" />
      </head>
      <body className="body">
        <div id="wrapper">
          <div id="page" className="">
            {children}
          </div>
        </div>
        {/* Scripts */}
        <Script src="/js/jquery.min.js" strategy="beforeInteractive" />
        <Script src="/js/bootstrap.min.js" strategy="afterInteractive" />
        <Script src="/js/bootstrap-select.min.js" strategy="afterInteractive" />
        <Script src="/js/zoom.js" strategy="afterInteractive" />
        <Script src="/js/jvectormap-1.2.2.min.js" strategy="afterInteractive" />
        <Script src="/js/jvectormap-us-lcc.js" strategy="afterInteractive" />
        <Script src="/js/jvectormap.js" strategy="afterInteractive" />
        <Script
          src="/js/apexcharts/apexcharts.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-1.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-2.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-3.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-4.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-7.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-17.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-18.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-19.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-20.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-21.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/apexcharts/line-chart-22.js"
          strategy="afterInteractive"
        />
        <Script src="/js/switcher.js" strategy="afterInteractive" />
        <Script src="/js/theme-settings.js" strategy="afterInteractive" />
        <Script src="/js/main.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
